name: rustfmt-check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cargo fmt --all -- --check
        cd ctoybox && cargo fmt --all -- --check
